name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Output Parameters
        run: |
          echo "Previous Tag ${{ steps.tag.outputs.previous_tag }}"
          echo "New Tag ${{ steps.tag.outputs.new_tag }}"