name: bump version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check output parameters
        run: |
          echo "Previous Tag ${{ steps.tag_version.outputs.previous_tag }}"
          echo "New Tag ${{ steps.tag_version.outputs.new_tag }}"
